# Generated by Django 5.1.1 on 2024-11-13 22:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("task", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="closed",
            field=models.BooleanField(default=False),
        ),
    ]
